# -----------------------------------------------------------------------------
# scls
[language-server.scls]
command = "simple-completion-language-server"
[language-server.scls.config]
max_completion_items = 20            # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
feature_unicode_input = true         # enable "unicode input"
feature_paths = true                 # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)
# -----------------------------------------------------------------------------
# typescript
[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server", "emmet-ls", "eslint", "scls"]
# -----------------------------------------------------------------------------
# javascript
[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "javascript"] }
auto-format = true
language-servers = ["typescript-language-server", "eslint"]
# -----------------------------------------------------------------------------
# html 
[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true
language-servers = ["vscode-html-language-server", "emmet-ls"]
# -----------------------------------------------------------------------------
# typescriptreact
[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server", "eslint", "emmet-ls"]
# -----------------------------------------------------------------------------
# # javascriptreact
[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "javascript"] }
auto-format = true
language-servers = ["typescript-language-server", "eslint", "emmet-ls"]
# -----------------------------------------------------------------------------
# # emmet ls
[language-server.emmet-ls]
name = "emmet-ls"
command = "emmet-ls"
args = ["--stdio"]
# -----------------------------------------------------------------------------
